language: node_js

node_js:
  - "0.10"
  - "0.12"

sudo: false

branches:
  except:
    - gh-pages

script:
  #- npm test --cover

after_script:
  - if [[ `node --version` == *v0.12* ]]; then cat ./build/coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js; fi
  
notifications:
  webhooks: https://coveralls.io/webhook?repo_token=COVERALLS_REPO_TOKEN
